In [1]:
# numpy

In [3]:
import numpy as np


In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
type(a)

numpy.ndarray

In [8]:
type(b)

numpy.ndarray

In [9]:
len(a)

3

In [10]:
len(b)

2

In [11]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
len(c)

3

In [13]:
a.ndim

1

In [14]:
b.ndim

2

In [15]:
c.ndim

2

In [16]:
a.shape

(3,)

In [17]:
b.shape

(2, 3)

In [18]:
c.shape

(3, 3)

In [19]:
a

array([1., 2., 3.])

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a.dtype

dtype('float64')

In [23]:
b.dtype

dtype('int32')

In [24]:
c.dtype

dtype('int32')

In [25]:
a=np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
a.ndim

2

In [28]:
a[0,3]

4

In [29]:
a[1,0]

8

In [30]:
a[1,4]

12

In [32]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [34]:
a[0,3]=40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
a[0,4]=50
print(a)

[[ 1  2  3 40 50  6  7]
 [ 8  9 10 11 12 13 14]]


In [38]:
np.zeros((3,3))
np.zeros((3,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.full(((3,3)),50,dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [42]:
np.random.randint(-4,1,size=(3,3))

array([[-1, -1,  0],
       [-2,  0, -4],
       [-3, -2, -4]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
 np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
#arethematic operation 
a+2

array([[ 3,  4,  5, 42, 52,  8,  9],
       [10, 11, 12, 13, 14, 15, 16]])

In [46]:
a**3

array([[     1,      8,     27,  64000, 125000,    216,    343],
       [   512,    729,   1000,   1331,   1728,   2197,   2744]],
      dtype=int32)

In [48]:

a.mean()

13.285714285714286

In [52]:
a.max()

50

In [53]:
a.min()

1

In [55]:
a.sum()

186